# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'marvelpedia' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for marvelpedia

  pod 'Firebase/Core'


  target 'marvelpediaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'marvelpedia-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for marvelpedia-tvOS

  target 'marvelpedia-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
